juju:
  channel: 3.5/stable

providers:
  k8s:
    enable: true
    bootstrap: true
    channel: 1.32-classic/stable

  lxd:
    enable: true
    bootstrap: false

host:
  snaps:
    charmcraft:
      channel: 3.x/stable
