juju:
  channel: 3.6/stable

providers:
  k8s:
    enable: true
    bootstrap: true
    channel: 1.32-classic/stable
    features:
      local-storage:
    bootstrap-constraints:
      root-disk: 2G

  lxd:
    enable: true
    bootstrap: false

host:
  snaps:
    charmcraft:
      channel: 3.x/stable
